"""GitHub PR commenter — post test results as PR comments.

Uses a reusable httpx.AsyncClient for connection pooling (best practice).
"""

from __future__ import annotations

import httpx
import structlog

from app.config import settings

logger = structlog.get_logger()

_GITHUB_API = "https://api.github.com"
_TIMEOUT = httpx.Timeout(15.0, connect=5.0)


class GitHubCommenter:
    """Post test results as comments on GitHub Pull Requests."""

    def __init__(self, token: str | None = None):
        self._token = token or settings.github_token
        self._headers = {
            "Authorization": f"Bearer {self._token}",
            "Accept": "application/vnd.github+json",
            "X-GitHub-Api-Version": "2022-11-28",
        }
        self._client: httpx.AsyncClient | None = None

    @property
    def is_configured(self) -> bool:
        return bool(self._token)

    async def _get_client(self) -> httpx.AsyncClient:
        if self._client is None or self._client.is_closed:
            self._client = httpx.AsyncClient(
                base_url=_GITHUB_API,
                headers=self._headers,
                timeout=_TIMEOUT,
            )
        return self._client

    async def close(self) -> None:
        if self._client and not self._client.is_closed:
            await self._client.aclose()

    async def post_results_comment(
        self,
        repo: str,
        pr_number: int,
        execution_id: str,
        passed: int,
        failed: int,
        skipped: int,
        coverage: float,
        verdict: str | None = None,
    ) -> bool:
        if not self.is_configured:
            logger.info("github_skip_not_configured")
            return False

        status_emoji = "✅" if failed == 0 else "❌"
        total = passed + failed + skipped

        body = (
            f"## {status_emoji} QA Nexus Test Results\n\n"
            f"| Metric | Value |\n"
            f"|--------|-------|\n"
            f"| **Execution** | `{execution_id}` |\n"
            f"| **Total Tests** | {total} |\n"
            f"| **Passed** | ✅ {passed} |\n"
            f"| **Failed** | ❌ {failed} |\n"
            f"| **Skipped** | ⏭️ {skipped} |\n"
            f"| **Coverage** | {coverage}% |\n"
            f"| **Verdict** | **{verdict or 'PENDING'}** |\n\n"
            f"---\n"
            f"*Generated by QA Nexus AI Testing Pipeline*"
        )

        try:
            client = await self._get_client()
            resp = await client.post(
                f"/repos/{repo}/issues/{pr_number}/comments",
                json={"body": body},
            )
            resp.raise_for_status()
            logger.info("github_comment_posted", repo=repo, pr=pr_number)
            return True
        except Exception as e:
            logger.error("github_comment_failed", repo=repo, pr=pr_number, error=str(e))
            return False

    async def create_check_run(
        self,
        repo: str,
        commit_sha: str,
        passed: int,
        failed: int,
        conclusion: str = "success",
    ) -> bool:
        if not self.is_configured:
            return False

        payload = {
            "name": "QA Nexus",
            "head_sha": commit_sha,
            "status": "completed",
            "conclusion": "success" if failed == 0 else "failure",
            "output": {
                "title": f"{'✅ All Passed' if failed == 0 else f'❌ {failed} Failed'}",
                "summary": f"Passed: {passed}, Failed: {failed}",
            },
        }

        try:
            client = await self._get_client()
            resp = await client.post(f"/repos/{repo}/check-runs", json=payload)
            resp.raise_for_status()
            return True
        except Exception as e:
            logger.error("github_check_run_failed", error=str(e))
            return False
