"""Email notification — send test results via SMTP."""

from __future__ import annotations

import asyncio
import smtplib
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from html import escape as html_escape

import structlog

from app.config import settings
from app.integrations.notifications.base import BaseNotifier, NotificationPayload

logger = structlog.get_logger()


class EmailNotifier(BaseNotifier):
    """Send pipeline results via SMTP email."""

    channel_name = "email"

    def __init__(
        self,
        smtp_host: str | None = None,
        smtp_port: int | None = None,
        smtp_user: str | None = None,
        smtp_password: str | None = None,
        from_address: str | None = None,
        to_addresses: list[str] | None = None,
    ):
        self._host = smtp_host or settings.smtp_host
        self._port = smtp_port or settings.smtp_port
        self._user = smtp_user or settings.smtp_user
        self._password = smtp_password or settings.smtp_password
        self._from = from_address or settings.email_from
        self._to = to_addresses or settings.email_to

    def is_configured(self) -> bool:
        return bool(self._host and self._to)

    async def send(self, payload: NotificationPayload) -> bool:
        if not self.is_configured():
            return False

        status = "✅ PASSED" if payload.is_success else "❌ FAILED"
        subject = f"QA Nexus — {payload.story_id} {status}"

        html = f"""
        <html>
        <body style="font-family: Arial, sans-serif;">
        <h2>QA Nexus Test Results</h2>
        <table border="1" cellpadding="8" cellspacing="0" style="border-collapse: collapse;">
            <tr><td><strong>Story</strong></td><td>{payload.story_id} — {payload.story_title}</td></tr>
            <tr><td><strong>Execution</strong></td><td><code>{payload.execution_id}</code></td></tr>
            <tr><td><strong>Status</strong></td><td>{status}</td></tr>
            <tr><td><strong>Passed</strong></td><td>{payload.passed}</td></tr>
            <tr><td><strong>Failed</strong></td><td>{payload.failed}</td></tr>
            <tr><td><strong>Coverage</strong></td><td>{payload.coverage}%</td></tr>
            <tr><td><strong>Verdict</strong></td><td>{payload.verdict or 'PENDING'}</td></tr>
        </table>
        {"<p style='color:red;'><strong>Error:</strong> " + html_escape(payload.error) + "</p>" if payload.error else ""}
        <hr>
        <p style="color: #666; font-size: 12px;">Generated by QA Nexus AI Testing Pipeline</p>
        </body>
        </html>
        """

        msg = MIMEMultipart("alternative")
        msg["Subject"] = subject
        msg["From"] = self._from
        msg["To"] = ", ".join(self._to)
        msg.attach(MIMEText(payload.summary, "plain"))
        msg.attach(MIMEText(html, "html"))

        try:
            # Run SMTP in thread pool to avoid blocking
            loop = asyncio.get_running_loop()
            await loop.run_in_executor(None, self._send_sync, msg)
            logger.info("email_sent", execution_id=payload.execution_id, to=self._to)
            return True
        except Exception as e:
            logger.error("email_failed", execution_id=payload.execution_id, error=str(e))
            return False

    def _send_sync(self, msg: MIMEMultipart) -> None:
        """Synchronous SMTP send (called in thread pool)."""
        if self._port == 465:
            with smtplib.SMTP_SSL(self._host, self._port) as server:
                if self._user and self._password:
                    server.login(self._user, self._password)
                server.send_message(msg)
        else:
            with smtplib.SMTP(self._host, self._port) as server:
                server.starttls()
                if self._user and self._password:
                    server.login(self._user, self._password)
                server.send_message(msg)
